name: CI/CD - Backend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run unit tests
      run: |
        PYTHONPATH=. pytest

    - name: Lint code
      run: |
        flake8 app.py

    - name: Build Docker image
      run: |
        docker build -t ivosalumbides/simple-notes-app-backend:latest .

    - name: Push Docker image
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Docker Push
      run: |
        docker push ivosalumbides/simple-notes-app-backend:latest
#