name: Hybrid CI/CD - Backend (DockerHub + GitHub OCI)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run unit tests
      run: PYTHONPATH=. pytest

    - name: Lint code
      run: flake8 app.py

    # Generate version using GitHub Run Number
    - name: Set Docker image tag
      id: vars
      run: |
        TAG="v1.0.${{ github.run_number }}"
        echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV

    ##########################
    # DockerHub Section
    ##########################
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image (DockerHub)
      run: |
        docker build -t ivosalumbides/simple-notes-app-backend:${{ env.IMAGE_TAG }} .
        docker tag ivosalumbides/simple-notes-app-backend:${{ env.IMAGE_TAG }} ivosalumbides/simple-notes-app-backend:latest

    - name: Push Docker Image (DockerHub)
      run: |
        docker push ivosalumbides/simple-notes-app-backend:${{ env.IMAGE_TAG }}
        docker push ivosalumbides/simple-notes-app-backend:latest

    ##########################
    # GitHub OCI Section
    ##########################
    - name: Login to GitHub OCI Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GH_PAT }}

    - name: Tag & Push Docker Image (GitHub OCI)
      run: |
        IMAGE_NAME=ghcr.io/${{ secrets.GHCR_USERNAME }}/simple-notes-app-backend
        docker tag ivosalumbides/simple-notes-app-backend:${{ env.IMAGE_TAG }} $IMAGE_NAME:${{ env.IMAGE_TAG }}
        docker tag ivosalumbides/simple-notes-app-backend:${{ env.IMAGE_TAG }} $IMAGE_NAME:latest
        docker push $IMAGE_NAME:${{ env.IMAGE_TAG }}
        docker push $IMAGE_NAME:latest
