name: CI/CD - Backend

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run unit tests
      run: PYTHONPATH=. pytest

    - name: Lint code
      run: flake8 app.py

    # Read version from git tags (autoversioning)
    - name: Get version from git tags
      id: get_version
      run: |
        TAG=$(git describe --tags --abbrev=0 || echo "v0.0.0")
        echo "Current version: $TAG"
        echo "CURRENT_VERSION=${TAG}" >> $GITHUB_ENV

    # Bump patch version automatically
    - name: Bump patch version
      id: bump_version
      run: |
        NEW_VERSION=$(echo ${{ env.CURRENT_VERSION }} | awk -F. -v OFS=. '{$NF += 1 ; print}')
        echo "New version: $NEW_VERSION"
        echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV

    # Build Docker image with new version
    - name: Build Docker image
      run: |
        docker build -t ivosalumbides/simple-notes-app-backend:${{ env.NEW_VERSION }} .
        docker tag ivosalumbides/simple-notes-app-backend:${{ env.NEW_VERSION }} ivosalumbides/simple-notes-app-backend:latest

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: |
        docker push ivosalumbides/simple-notes-app-backend:${{ env.NEW_VERSION }}
        docker push ivosalumbides/simple-notes-app-backend:latest
