name: Hybrid CI/CD - Backend (DockerHub + GitHub OCI) [Upgraded Phase 1]

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    ##############################
    # Checkout Code
    ##############################
    - name: Checkout code
      uses: actions/checkout@v3

    ##############################
    # Setup Python
    ##############################
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    ##############################
    # Install Dependencies
    ##############################
    - name: Install dependencies
      run: pip install -r requirements.txt

    ##############################
    # Unit Tests
    ##############################
    - name: Run unit tests
      run: PYTHONPATH=. pytest

    ##############################
    # Linting with strict mode
    ##############################
    - name: Lint code
      run: flake8 --max-line-length=88 --statistics --count app.py

    ##############################
    # Set Docker Image Tag
    ##############################
    - name: Set Docker image tag
      id: vars
      run: |
        TAG="v1.0.${{ github.run_number }}"
        echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV

    ##############################
    # DockerHub Section
    ##############################
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image (DockerHub)
      run: |
        docker build -t ivosalumbides/simple-notes-app-backend:${{ env.IMAGE_TAG }} .
        docker tag ivosalumbides/simple-notes-app-backend:${{ env.IMAGE_TAG }} ivosalumbides/simple-notes-app-backend:latest

    - name: Push Docker Image (DockerHub)
      run: |
        docker push ivosalumbides/simple-notes-app-backend:${{ env.IMAGE_TAG }}
        docker push ivosalumbides/simple-notes-app-backend:latest

    ##############################
    # Security Scan using Trivy
    ##############################
    - name: Security Scan (Trivy)
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ivosalumbides/simple-notes-app-backend:${{ env.IMAGE_TAG }}
      continue-on-error: true  # (safe mode: hindi i-fail ang pipeline kapag may CVEs, for learning stage)

    ##############################
    # GitHub OCI Section
    ##############################
    - name: Login to GitHub OCI Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GH_PAT }}

    - name: Tag & Push Docker Image (GitHub OCI)
      run: |
        IMAGE_NAME=ghcr.io/${{ secrets.GHCR_USERNAME }}/simple-notes-app-backend
        docker tag ivosalumbides/simple-notes-app-backend:${{ env.IMAGE_TAG }} $IMAGE_NAME:${{ env.IMAGE_TAG }}
        docker tag ivosalumbides/simple-notes-app-backend:${{ env.IMAGE_TAG }} $IMAGE_NAME:latest
        docker push $IMAGE_NAME:${{ env.IMAGE_TAG }}
        docker push $IMAGE_NAME:latest
